allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}
font_family RobotoMono Nerd Font Mono
font_size 20.0
cursor_shape beam
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{index}: {title}"
map cmd+d launch --location=vsplit
map cmd+s launch --location=hsplit
map cmd+shift+d close_window
map cmd+t new_tab
map cmd+shift+t close_tab
map cmd+n next_tab
map cmd+m previous_tab
# avoid silly characters in the prompt 
map cmd+c copy_or_interrupt
map cmd+shift+c reload_config
