font_family RobotoMono Nerd Font Mono
font_size 20.0
cursor_shape beam
map cmd+d launch --location=vsplit
map cmd+shift+d close_window
map cmd+t new_tab
map cmd+shift+t close_tab
map cmd+shift+l next_tab
map cmd+shift+j previous_tab
# avoid silly characters in the prompt 
map cmd+c copy_or_interrupt
map cmd+shift+c reload_config
