font_family RobotoMono Nerd Font Mono
font_size 20.0
include current-theme.conf

map cmd+d launch --location=vsplit
map cmd+shift+d launch --location=hsplit


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME